ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODY4NzA4MzA2LjE3NDU0NDEwOTUifSwiYW5vbklkIjoiMDVhNWZhOTNiNWVlNjhiMSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjY4MTQ4NDg2Mjc2NDU2MTUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e89a81ccea <unknown>
#1 0x55e89a2cd5f0 <unknown>
#2 0x55e89a2b3e86 <unknown>
#3 0x55e89a2b279a <unknown>
#4 0x55e89a2b2eff <unknown>
#5 0x55e89a2b2e54 <unknown>
#6 0x55e89a2d17ff <unknown>
#7 0x55e89a3769aa <unknown>
#8 0x55e89a344662 <unknown>
#9 0x55e89a36a660 <unknown>
#10 0x55e89a344433 <unknown>
#11 0x55e89a310ea3 <unknown>
#12 0x55e89a311b01 <unknown>
#13 0x55e89a7e1b3b <unknown>
#14 0x55e89a7e5a21 <unknown>
#15 0x55e89a7c8c32 <unknown>
#16 0x55e89a7e6594 <unknown>
#17 0x55e89a7aceef <unknown>
#18 0x55e89a80ad98 <unknown>
#19 0x55e89a80af76 <unknown>
#20 0x55e89a81bb36 <unknown>
#21 0x7fafb2c9caa4 <unknown>
#22 0x7fafb2d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNjcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg2ODcwODMwNi4xNzQ1NDQxMDk1In0sImFub25JZCI6IjA1YTVmYTkzYjVlZTY4YjEifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjE2NzEiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjE2NzEiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1MDgwOTE3MDMwODA4MzUzIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e89a81ccea <unknown>
#1 0x55e89a2cd5f0 <unknown>
#2 0x55e89a2b3e86 <unknown>
#3 0x55e89a2b279a <unknown>
#4 0x55e89a2b2eff <unknown>
#5 0x55e89a2b2e54 <unknown>
#6 0x55e89a2d17ff <unknown>
#7 0x55e89a3769aa <unknown>
#8 0x55e89a344662 <unknown>
#9 0x55e89a36a660 <unknown>
#10 0x55e89a344433 <unknown>
#11 0x55e89a310ea3 <unknown>
#12 0x55e89a311b01 <unknown>
#13 0x55e89a7e1b3b <unknown>
#14 0x55e89a7e5a21 <unknown>
#15 0x55e89a7c8c32 <unknown>
#16 0x55e89a7e6594 <unknown>
#17 0x55e89a7aceef <unknown>
#18 0x55e89a80ad98 <unknown>
#19 0x55e89a80af76 <unknown>
#20 0x55e89a81bb36 <unknown>
#21 0x7fafb2c9caa4 <unknown>
#22 0x7fafb2d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg2ODcwODMwNi4xNzQ1NDQxMDk1In0sImFub25JZCI6IjA1YTVmYTkzYjVlZTY4YjEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE5MjE3MzIzODYyMDA0MTU0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e89a81ccea <unknown>
#1 0x55e89a2cd5f0 <unknown>
#2 0x55e89a2b3e86 <unknown>
#3 0x55e89a2b279a <unknown>
#4 0x55e89a2b2eff <unknown>
#5 0x55e89a2b2e54 <unknown>
#6 0x55e89a2d17ff <unknown>
#7 0x55e89a3769aa <unknown>
#8 0x55e89a344662 <unknown>
#9 0x55e89a36a660 <unknown>
#10 0x55e89a344433 <unknown>
#11 0x55e89a310ea3 <unknown>
#12 0x55e89a311b01 <unknown>
#13 0x55e89a7e1b3b <unknown>
#14 0x55e89a7e5a21 <unknown>
#15 0x55e89a7c8c32 <unknown>
#16 0x55e89a7e6594 <unknown>
#17 0x55e89a7aceef <unknown>
#18 0x55e89a80ad98 <unknown>
#19 0x55e89a80af76 <unknown>
#20 0x55e89a81bb36 <unknown>
#21 0x7fafb2c9caa4 <unknown>
#22 0x7fafb2d29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjE2Ny1mbCIsInZlaGljbGVCTSI6IjE2NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMTY3MSIsInRpbWVzdGFtcCI6MTc0NTQ0MTA5ODYxMywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg2ODcwODMwNi4xNzQ1NDQxMDk1In0sImFub25JZCI6IjA1YTVmYTkzYjVlZTY4YjEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMzMxOTQxNjIxMzE0ODEwMyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e89a81ccea <unknown>
#1 0x55e89a2cd5f0 <unknown>
#2 0x55e89a2b3e86 <unknown>
#3 0x55e89a2b279a <unknown>
#4 0x55e89a2b2eff <unknown>
#5 0x55e89a2b2e54 <unknown>
#6 0x55e89a2d17ff <unknown>
#7 0x55e89a3769aa <unknown>
#8 0x55e89a344662 <unknown>
#9 0x55e89a36a660 <unknown>
#10 0x55e89a344433 <unknown>
#11 0x55e89a310ea3 <unknown>
#12 0x55e89a311b01 <unknown>
#13 0x55e89a7e1b3b <unknown>
#14 0x55e89a7e5a21 <unknown>
#15 0x55e89a7c8c32 <unknown>
#16 0x55e89a7e6594 <unknown>
#17 0x55e89a7aceef <unknown>
#18 0x55e89a80ad98 <unknown>
#19 0x55e89a80af76 <unknown>
#20 0x55e89a81bb36 <unknown>
#21 0x7fafb2c9caa4 <unknown>
#22 0x7fafb2d29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252cf0610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252cf1590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252cf1c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNjcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjEzZGYxNWFlZWU0M2JjNTAifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTY3MSIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTY3MSJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjExOTI4NzkzMzQ4NDQ4OTYzIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5571613ebcea <unknown>
#1 0x557160e9c5f0 <unknown>
#2 0x557160e82e86 <unknown>
#3 0x557160e8179a <unknown>
#4 0x557160e81eff <unknown>
#5 0x557160e81e54 <unknown>
#6 0x557160ea07ff <unknown>
#7 0x557160f459aa <unknown>
#8 0x557160f13662 <unknown>
#9 0x557160f39660 <unknown>
#10 0x557160f13433 <unknown>
#11 0x557160edfea3 <unknown>
#12 0x557160ee0b01 <unknown>
#13 0x5571613b0b3b <unknown>
#14 0x5571613b4a21 <unknown>
#15 0x557161397c32 <unknown>
#16 0x5571613b5594 <unknown>
#17 0x55716137beef <unknown>
#18 0x5571613d9d98 <unknown>
#19 0x5571613d9f76 <unknown>
#20 0x5571613eab36 <unknown>
#21 0x7f0c80a9caa4 <unknown>
#22 0x7f0c80b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiMTNkZjE1YWVlZTQzYmM1MCJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc0MTI2NTAzNjI0MDQ0NjUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5571613ebcea <unknown>
#1 0x557160e9c5f0 <unknown>
#2 0x557160e82e86 <unknown>
#3 0x557160e8179a <unknown>
#4 0x557160e81eff <unknown>
#5 0x557160e81e54 <unknown>
#6 0x557160ea07ff <unknown>
#7 0x557160f459aa <unknown>
#8 0x557160f13662 <unknown>
#9 0x557160f39660 <unknown>
#10 0x557160f13433 <unknown>
#11 0x557160edfea3 <unknown>
#12 0x557160ee0b01 <unknown>
#13 0x5571613b0b3b <unknown>
#14 0x5571613b4a21 <unknown>
#15 0x557161397c32 <unknown>
#16 0x5571613b5594 <unknown>
#17 0x55716137beef <unknown>
#18 0x5571613d9d98 <unknown>
#19 0x5571613d9f76 <unknown>
#20 0x5571613eab36 <unknown>
#21 0x7f0c80a9caa4 <unknown>
#22 0x7f0c80b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiIxM2RmMTVhZWVlNDNiYzUwIn0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDUwNzMwMzAxMTc2MzAzNjQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5571613ebcea <unknown>
#1 0x557160e9c5f0 <unknown>
#2 0x557160e82e86 <unknown>
#3 0x557160e8179a <unknown>
#4 0x557160e81eff <unknown>
#5 0x557160e81e54 <unknown>
#6 0x557160ea07ff <unknown>
#7 0x557160f459aa <unknown>
#8 0x557160f13662 <unknown>
#9 0x557160f39660 <unknown>
#10 0x557160f13433 <unknown>
#11 0x557160edfea3 <unknown>
#12 0x557160ee0b01 <unknown>
#13 0x5571613b0b3b <unknown>
#14 0x5571613b4a21 <unknown>
#15 0x557161397c32 <unknown>
#16 0x5571613b5594 <unknown>
#17 0x55716137beef <unknown>
#18 0x5571613d9d98 <unknown>
#19 0x5571613d9f76 <unknown>
#20 0x5571613eab36 <unknown>
#21 0x7f0c80a9caa4 <unknown>
#22 0x7f0c80b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjE2Ny1mbCIsInZlaGljbGVCTSI6IjE2NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMTY3MSIsInRpbWVzdGFtcCI6MTc0NTQ0MTEzMzQ4MSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2NTY1NjA2ODkuMTc0NTQ0MTEzMSJ9LCJhbm9uSWQiOiIxM2RmMTVhZWVlNDNiYzUwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjA1NDQ0ODIzOTc5NTAwNjc5IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5571613ebcea <unknown>
#1 0x557160e9c5f0 <unknown>
#2 0x557160e82e86 <unknown>
#3 0x557160e8179a <unknown>
#4 0x557160e81eff <unknown>
#5 0x557160e81e54 <unknown>
#6 0x557160ea07ff <unknown>
#7 0x557160f459aa <unknown>
#8 0x557160f13662 <unknown>
#9 0x557160f39660 <unknown>
#10 0x557160f13433 <unknown>
#11 0x557160edfea3 <unknown>
#12 0x557160ee0b01 <unknown>
#13 0x5571613b0b3b <unknown>
#14 0x5571613b4a21 <unknown>
#15 0x557161397c32 <unknown>
#16 0x5571613b5594 <unknown>
#17 0x55716137beef <unknown>
#18 0x5571613d9d98 <unknown>
#19 0x5571613d9f76 <unknown>
#20 0x5571613eab36 <unknown>
#21 0x7f0c80a9caa4 <unknown>
#22 0x7f0c80b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251887110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251884f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62518867d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c00b1eddde389be000f17424a9234c92