ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMjkxNjA1NTcuMTc0NTQzOTk3NSJ9LCJhbm9uSWQiOiI3NmY1MmU4ZDc0YzM1ODc3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3NDAzMDUzMDUyMjc0ODA0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556409c57cea <unknown>
#1 0x5564097085f0 <unknown>
#2 0x5564096eee86 <unknown>
#3 0x5564096ed79a <unknown>
#4 0x5564096edeff <unknown>
#5 0x5564096ede54 <unknown>
#6 0x55640970c7ff <unknown>
#7 0x5564097b19aa <unknown>
#8 0x55640977f662 <unknown>
#9 0x5564097a5660 <unknown>
#10 0x55640977f433 <unknown>
#11 0x55640974bea3 <unknown>
#12 0x55640974cb01 <unknown>
#13 0x556409c1cb3b <unknown>
#14 0x556409c20a21 <unknown>
#15 0x556409c03c32 <unknown>
#16 0x556409c21594 <unknown>
#17 0x556409be7eef <unknown>
#18 0x556409c45d98 <unknown>
#19 0x556409c45f76 <unknown>
#20 0x556409c56b36 <unknown>
#21 0x7fb69f29caa4 <unknown>
#22 0x7fb69f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjEyOTE2MDU1Ny4xNzQ1NDM5OTc1In0sImFub25JZCI6Ijc2ZjUyZThkNzRjMzU4NzcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjkxMDAxNDc0MzUxMDcyNzMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556409c57cea <unknown>
#1 0x5564097085f0 <unknown>
#2 0x5564096eee86 <unknown>
#3 0x5564096ed79a <unknown>
#4 0x5564096edeff <unknown>
#5 0x5564096ede54 <unknown>
#6 0x55640970c7ff <unknown>
#7 0x5564097b19aa <unknown>
#8 0x55640977f662 <unknown>
#9 0x5564097a5660 <unknown>
#10 0x55640977f433 <unknown>
#11 0x55640974bea3 <unknown>
#12 0x55640974cb01 <unknown>
#13 0x556409c1cb3b <unknown>
#14 0x556409c20a21 <unknown>
#15 0x556409c03c32 <unknown>
#16 0x556409c21594 <unknown>
#17 0x556409be7eef <unknown>
#18 0x556409c45d98 <unknown>
#19 0x556409c45f76 <unknown>
#20 0x556409c56b36 <unknown>
#21 0x7fb69f29caa4 <unknown>
#22 0x7fb69f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMjkxNjA1NTcuMTc0NTQzOTk3NSJ9LCJhbm9uSWQiOiI3NmY1MmU4ZDc0YzM1ODc3In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNTQzIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNTQzIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODczNTA5OTQ4NTcxOTI1MiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556409c57cea <unknown>
#1 0x5564097085f0 <unknown>
#2 0x5564096eee86 <unknown>
#3 0x5564096ed79a <unknown>
#4 0x5564096edeff <unknown>
#5 0x5564096ede54 <unknown>
#6 0x55640970c7ff <unknown>
#7 0x5564097b19aa <unknown>
#8 0x55640977f662 <unknown>
#9 0x5564097a5660 <unknown>
#10 0x55640977f433 <unknown>
#11 0x55640974bea3 <unknown>
#12 0x55640974cb01 <unknown>
#13 0x556409c1cb3b <unknown>
#14 0x556409c20a21 <unknown>
#15 0x556409c03c32 <unknown>
#16 0x556409c21594 <unknown>
#17 0x556409be7eef <unknown>
#18 0x556409c45d98 <unknown>
#19 0x556409c45f76 <unknown>
#20 0x556409c56b36 <unknown>
#21 0x7fb69f29caa4 <unknown>
#22 0x7fb69f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYzI1NCIsInZlaGljbGVCTSI6IjI1NDMiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0MyIsInRpbWVzdGFtcCI6MTc0NTQzOTk3OTQzNiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMjkxNjA1NTcuMTc0NTQzOTk3NSJ9LCJhbm9uSWQiOiI3NmY1MmU4ZDc0YzM1ODc3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6Ijk1NTAyMDkxMDI4NTc4NzYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556409c57cea <unknown>
#1 0x5564097085f0 <unknown>
#2 0x5564096eee86 <unknown>
#3 0x5564096ed79a <unknown>
#4 0x5564096edeff <unknown>
#5 0x5564096ede54 <unknown>
#6 0x55640970c7ff <unknown>
#7 0x5564097b19aa <unknown>
#8 0x55640977f662 <unknown>
#9 0x5564097a5660 <unknown>
#10 0x55640977f433 <unknown>
#11 0x55640974bea3 <unknown>
#12 0x55640974cb01 <unknown>
#13 0x556409c1cb3b <unknown>
#14 0x556409c20a21 <unknown>
#15 0x556409c03c32 <unknown>
#16 0x556409c21594 <unknown>
#17 0x556409be7eef <unknown>
#18 0x556409c45d98 <unknown>
#19 0x556409c45f76 <unknown>
#20 0x556409c56b36 <unknown>
#21 0x7fb69f29caa4 <unknown>
#22 0x7fb69f329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6eb2010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6eb3610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6eb0090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEwMzE4MjI4ODAuMTc0NTQ0MDAwOSJ9LCJhbm9uSWQiOiIyN2UyMjhkNWViYTc4MDY1In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMTY1NjE4OTA1NTA4NzA2MyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563707157cea <unknown>
#1 0x563706c085f0 <unknown>
#2 0x563706beee86 <unknown>
#3 0x563706bed79a <unknown>
#4 0x563706bedeff <unknown>
#5 0x563706bede54 <unknown>
#6 0x563706c0c7ff <unknown>
#7 0x563706cb19aa <unknown>
#8 0x563706c7f662 <unknown>
#9 0x563706ca5660 <unknown>
#10 0x563706c7f433 <unknown>
#11 0x563706c4bea3 <unknown>
#12 0x563706c4cb01 <unknown>
#13 0x56370711cb3b <unknown>
#14 0x563707120a21 <unknown>
#15 0x563707103c32 <unknown>
#16 0x563707121594 <unknown>
#17 0x5637070e7eef <unknown>
#18 0x563707145d98 <unknown>
#19 0x563707145f76 <unknown>
#20 0x563707156b36 <unknown>
#21 0x7fe178a9caa4 <unknown>
#22 0x7fe178b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTAzMTgyMjg4MC4xNzQ1NDQwMDA5In0sImFub25JZCI6IjI3ZTIyOGQ1ZWJhNzgwNjUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU2ODM2MDU0ODE4MDUxNiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563707157cea <unknown>
#1 0x563706c085f0 <unknown>
#2 0x563706beee86 <unknown>
#3 0x563706bed79a <unknown>
#4 0x563706bedeff <unknown>
#5 0x563706bede54 <unknown>
#6 0x563706c0c7ff <unknown>
#7 0x563706cb19aa <unknown>
#8 0x563706c7f662 <unknown>
#9 0x563706ca5660 <unknown>
#10 0x563706c7f433 <unknown>
#11 0x563706c4bea3 <unknown>
#12 0x563706c4cb01 <unknown>
#13 0x56370711cb3b <unknown>
#14 0x563707120a21 <unknown>
#15 0x563707103c32 <unknown>
#16 0x563707121594 <unknown>
#17 0x5637070e7eef <unknown>
#18 0x563707145d98 <unknown>
#19 0x563707145f76 <unknown>
#20 0x563707156b36 <unknown>
#21 0x7fe178a9caa4 <unknown>
#22 0x7fe178b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEwMzE4MjI4ODAuMTc0NTQ0MDAwOSJ9LCJhbm9uSWQiOiIyN2UyMjhkNWViYTc4MDY1In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNTQzIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNTQzIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTI4ODk1Mjc3OTM3ODA5MiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563707157cea <unknown>
#1 0x563706c085f0 <unknown>
#2 0x563706beee86 <unknown>
#3 0x563706bed79a <unknown>
#4 0x563706bedeff <unknown>
#5 0x563706bede54 <unknown>
#6 0x563706c0c7ff <unknown>
#7 0x563706cb19aa <unknown>
#8 0x563706c7f662 <unknown>
#9 0x563706ca5660 <unknown>
#10 0x563706c7f433 <unknown>
#11 0x563706c4bea3 <unknown>
#12 0x563706c4cb01 <unknown>
#13 0x56370711cb3b <unknown>
#14 0x563707120a21 <unknown>
#15 0x563707103c32 <unknown>
#16 0x563707121594 <unknown>
#17 0x5637070e7eef <unknown>
#18 0x563707145d98 <unknown>
#19 0x563707145f76 <unknown>
#20 0x563707156b36 <unknown>
#21 0x7fe178a9caa4 <unknown>
#22 0x7fe178b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYzI1NCIsInZlaGljbGVCTSI6IjI1NDMiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0MyIsInRpbWVzdGFtcCI6MTc0NTQ0MDAxMzMzNCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEwMzE4MjI4ODAuMTc0NTQ0MDAwOSJ9LCJhbm9uSWQiOiIyN2UyMjhkNWViYTc4MDY1In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjQ5MDkxMjc2MDkyNjY2OTkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563707157cea <unknown>
#1 0x563706c085f0 <unknown>
#2 0x563706beee86 <unknown>
#3 0x563706bed79a <unknown>
#4 0x563706bedeff <unknown>
#5 0x563706bede54 <unknown>
#6 0x563706c0c7ff <unknown>
#7 0x563706cb19aa <unknown>
#8 0x563706c7f662 <unknown>
#9 0x563706ca5660 <unknown>
#10 0x563706c7f433 <unknown>
#11 0x563706c4bea3 <unknown>
#12 0x563706c4cb01 <unknown>
#13 0x56370711cb3b <unknown>
#14 0x563707120a21 <unknown>
#15 0x563707103c32 <unknown>
#16 0x563707121594 <unknown>
#17 0x5637070e7eef <unknown>
#18 0x563707145d98 <unknown>
#19 0x563707145f76 <unknown>
#20 0x563707156b36 <unknown>
#21 0x7fe178a9caa4 <unknown>
#22 0x7fe178b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bcfa10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bcf190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bcd090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b7c007abe143db93afd8fc0056f9f407