ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2MjE2NTU5ODQuMTc0NTQ0OTc2NiJ9LCJhbm9uSWQiOiI4NjU2MzFjNDlhODEyNjNkIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MTU0OTU5OTgwNzcxMDM2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fb3ea2cea <unknown>
#1 0x560fb39535f0 <unknown>
#2 0x560fb3939e86 <unknown>
#3 0x560fb393879a <unknown>
#4 0x560fb3938eff <unknown>
#5 0x560fb3938e54 <unknown>
#6 0x560fb39577ff <unknown>
#7 0x560fb39fc9aa <unknown>
#8 0x560fb39ca662 <unknown>
#9 0x560fb39f0660 <unknown>
#10 0x560fb39ca433 <unknown>
#11 0x560fb3996ea3 <unknown>
#12 0x560fb3997b01 <unknown>
#13 0x560fb3e67b3b <unknown>
#14 0x560fb3e6ba21 <unknown>
#15 0x560fb3e4ec32 <unknown>
#16 0x560fb3e6c594 <unknown>
#17 0x560fb3e32eef <unknown>
#18 0x560fb3e90d98 <unknown>
#19 0x560fb3e90f76 <unknown>
#20 0x560fb3ea1b36 <unknown>
#21 0x7f170529caa4 <unknown>
#22 0x7f1705329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2MjE2NTU5ODQuMTc0NTQ0OTc2NiJ9LCJhbm9uSWQiOiI4NjU2MzFjNDlhODEyNjNkIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTcxIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTcxIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTg2MDA4NDI1ODM2NDQ4NyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fb3ea2cea <unknown>
#1 0x560fb39535f0 <unknown>
#2 0x560fb3939e86 <unknown>
#3 0x560fb393879a <unknown>
#4 0x560fb3938eff <unknown>
#5 0x560fb3938e54 <unknown>
#6 0x560fb39577ff <unknown>
#7 0x560fb39fc9aa <unknown>
#8 0x560fb39ca662 <unknown>
#9 0x560fb39f0660 <unknown>
#10 0x560fb39ca433 <unknown>
#11 0x560fb3996ea3 <unknown>
#12 0x560fb3997b01 <unknown>
#13 0x560fb3e67b3b <unknown>
#14 0x560fb3e6ba21 <unknown>
#15 0x560fb3e4ec32 <unknown>
#16 0x560fb3e6c594 <unknown>
#17 0x560fb3e32eef <unknown>
#18 0x560fb3e90d98 <unknown>
#19 0x560fb3e90f76 <unknown>
#20 0x560fb3ea1b36 <unknown>
#21 0x7f170529caa4 <unknown>
#22 0x7f1705329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYyMTY1NTk4NC4xNzQ1NDQ5NzY2In0sImFub25JZCI6Ijg2NTYzMWM0OWE4MTI2M2QifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI4MjEzODYwODQyNzU5MyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fb3ea2cea <unknown>
#1 0x560fb39535f0 <unknown>
#2 0x560fb3939e86 <unknown>
#3 0x560fb393879a <unknown>
#4 0x560fb3938eff <unknown>
#5 0x560fb3938e54 <unknown>
#6 0x560fb39577ff <unknown>
#7 0x560fb39fc9aa <unknown>
#8 0x560fb39ca662 <unknown>
#9 0x560fb39f0660 <unknown>
#10 0x560fb39ca433 <unknown>
#11 0x560fb3996ea3 <unknown>
#12 0x560fb3997b01 <unknown>
#13 0x560fb3e67b3b <unknown>
#14 0x560fb3e6ba21 <unknown>
#15 0x560fb3e4ec32 <unknown>
#16 0x560fb3e6c594 <unknown>
#17 0x560fb3e32eef <unknown>
#18 0x560fb3e90d98 <unknown>
#19 0x560fb3e90f76 <unknown>
#20 0x560fb3ea1b36 <unknown>
#21 0x7f170529caa4 <unknown>
#22 0x7f1705329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjI5NyIsInZlaGljbGVCTSI6IjI5NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk3MSIsInRpbWVzdGFtcCI6MTc0NTQ0OTc3NzExNiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2MjE2NTU5ODQuMTc0NTQ0OTc2NiJ9LCJhbm9uSWQiOiI4NjU2MzFjNDlhODEyNjNkIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6Ijg3MjI5NTA4NDU0MzYxNDgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fb3ea2cea <unknown>
#1 0x560fb39535f0 <unknown>
#2 0x560fb3939e86 <unknown>
#3 0x560fb393879a <unknown>
#4 0x560fb3938eff <unknown>
#5 0x560fb3938e54 <unknown>
#6 0x560fb39577ff <unknown>
#7 0x560fb39fc9aa <unknown>
#8 0x560fb39ca662 <unknown>
#9 0x560fb39f0660 <unknown>
#10 0x560fb39ca433 <unknown>
#11 0x560fb3996ea3 <unknown>
#12 0x560fb3997b01 <unknown>
#13 0x560fb3e67b3b <unknown>
#14 0x560fb3e6ba21 <unknown>
#15 0x560fb3e4ec32 <unknown>
#16 0x560fb3e6c594 <unknown>
#17 0x560fb3e32eef <unknown>
#18 0x560fb3e90d98 <unknown>
#19 0x560fb3e90f76 <unknown>
#20 0x560fb3ea1b36 <unknown>
#21 0x7f170529caa4 <unknown>
#22 0x7f1705329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a97d750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a97e4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a97e110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0NzIwNTUzNy4xNzQ1NDQ5ODE4In0sImFub25JZCI6IjAwZWEwZTY1Y2ZkMDUzNTgifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjV9LCJfdG9vbHNFdmVudExpbmtJZCI6IjkzNTcyMzczNjI5MDY3OTIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5605a5366cea <unknown>
#1 0x5605a4e175f0 <unknown>
#2 0x5605a4dfde86 <unknown>
#3 0x5605a4dfc79a <unknown>
#4 0x5605a4dfceff <unknown>
#5 0x5605a4dfce54 <unknown>
#6 0x5605a4e1b7ff <unknown>
#7 0x5605a4ec09aa <unknown>
#8 0x5605a4e8e662 <unknown>
#9 0x5605a4eb4660 <unknown>
#10 0x5605a4e8e433 <unknown>
#11 0x5605a4e5aea3 <unknown>
#12 0x5605a4e5bb01 <unknown>
#13 0x5605a532bb3b <unknown>
#14 0x5605a532fa21 <unknown>
#15 0x5605a5312c32 <unknown>
#16 0x5605a5330594 <unknown>
#17 0x5605a52f6eef <unknown>
#18 0x5605a5354d98 <unknown>
#19 0x5605a5354f76 <unknown>
#20 0x5605a5365b36 <unknown>
#21 0x7f86f509caa4 <unknown>
#22 0x7f86f5129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ3MjA1NTM3LjE3NDU0NDk4MTgifSwiYW5vbklkIjoiMDBlYTBlNjVjZmQwNTM1OCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zYWxvb24vZXFzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjc1OTI3MDkxMjMxNzkyNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5605a5366cea <unknown>
#1 0x5605a4e175f0 <unknown>
#2 0x5605a4dfde86 <unknown>
#3 0x5605a4dfc79a <unknown>
#4 0x5605a4dfceff <unknown>
#5 0x5605a4dfce54 <unknown>
#6 0x5605a4e1b7ff <unknown>
#7 0x5605a4ec09aa <unknown>
#8 0x5605a4e8e662 <unknown>
#9 0x5605a4eb4660 <unknown>
#10 0x5605a4e8e433 <unknown>
#11 0x5605a4e5aea3 <unknown>
#12 0x5605a4e5bb01 <unknown>
#13 0x5605a532bb3b <unknown>
#14 0x5605a532fa21 <unknown>
#15 0x5605a5312c32 <unknown>
#16 0x5605a5330594 <unknown>
#17 0x5605a52f6eef <unknown>
#18 0x5605a5354d98 <unknown>
#19 0x5605a5354f76 <unknown>
#20 0x5605a5365b36 <unknown>
#21 0x7f86f509caa4 <unknown>
#22 0x7f86f5129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0NzIwNTUzNy4xNzQ1NDQ5ODE4In0sImFub25JZCI6IjAwZWEwZTY1Y2ZkMDUzNTgifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjo1fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI5NzEiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI5NzEiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyMTcwNzU5ODY4ODI2Mzg2MyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5605a5366cea <unknown>
#1 0x5605a4e175f0 <unknown>
#2 0x5605a4dfde86 <unknown>
#3 0x5605a4dfc79a <unknown>
#4 0x5605a4dfceff <unknown>
#5 0x5605a4dfce54 <unknown>
#6 0x5605a4e1b7ff <unknown>
#7 0x5605a4ec09aa <unknown>
#8 0x5605a4e8e662 <unknown>
#9 0x5605a4eb4660 <unknown>
#10 0x5605a4e8e433 <unknown>
#11 0x5605a4e5aea3 <unknown>
#12 0x5605a4e5bb01 <unknown>
#13 0x5605a532bb3b <unknown>
#14 0x5605a532fa21 <unknown>
#15 0x5605a5312c32 <unknown>
#16 0x5605a5330594 <unknown>
#17 0x5605a52f6eef <unknown>
#18 0x5605a5354d98 <unknown>
#19 0x5605a5354f76 <unknown>
#20 0x5605a5365b36 <unknown>
#21 0x7f86f509caa4 <unknown>
#22 0x7f86f5129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjI5NyIsInZlaGljbGVCTSI6IjI5NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk3MSIsInRpbWVzdGFtcCI6MTc0NTQ0OTgyNzI3NiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0NzIwNTUzNy4xNzQ1NDQ5ODE4In0sImFub25JZCI6IjAwZWEwZTY1Y2ZkMDUzNTgifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMDc1Njk5NDM0NDY1MDIxNDgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5605a5366cea <unknown>
#1 0x5605a4e175f0 <unknown>
#2 0x5605a4dfde86 <unknown>
#3 0x5605a4dfc79a <unknown>
#4 0x5605a4dfceff <unknown>
#5 0x5605a4dfce54 <unknown>
#6 0x5605a4e1b7ff <unknown>
#7 0x5605a4ec09aa <unknown>
#8 0x5605a4e8e662 <unknown>
#9 0x5605a4eb4660 <unknown>
#10 0x5605a4e8e433 <unknown>
#11 0x5605a4e5aea3 <unknown>
#12 0x5605a4e5bb01 <unknown>
#13 0x5605a532bb3b <unknown>
#14 0x5605a532fa21 <unknown>
#15 0x5605a5312c32 <unknown>
#16 0x5605a5330594 <unknown>
#17 0x5605a52f6eef <unknown>
#18 0x5605a5354d98 <unknown>
#19 0x5605a5354f76 <unknown>
#20 0x5605a5365b36 <unknown>
#21 0x7f86f509caa4 <unknown>
#22 0x7f86f5129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a0f98250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a0f98550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a0f98c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6aa34778386e7c26db3a534f94ad386a