ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjA0NzQwMDY3OS4xNzQ1NDQ5NzczIn0sImFub25JZCI6IjA1NTU0YjhlZjkyMzZhZWYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA2MzAxODMxMTI1OTg3MDkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fea89cccea <unknown>
#1 0x55fea847d5f0 <unknown>
#2 0x55fea8463e86 <unknown>
#3 0x55fea846279a <unknown>
#4 0x55fea8462eff <unknown>
#5 0x55fea8462e54 <unknown>
#6 0x55fea84817ff <unknown>
#7 0x55fea85269aa <unknown>
#8 0x55fea84f4662 <unknown>
#9 0x55fea851a660 <unknown>
#10 0x55fea84f4433 <unknown>
#11 0x55fea84c0ea3 <unknown>
#12 0x55fea84c1b01 <unknown>
#13 0x55fea8991b3b <unknown>
#14 0x55fea8995a21 <unknown>
#15 0x55fea8978c32 <unknown>
#16 0x55fea8996594 <unknown>
#17 0x55fea895ceef <unknown>
#18 0x55fea89bad98 <unknown>
#19 0x55fea89baf76 <unknown>
#20 0x55fea89cbb36 <unknown>
#21 0x7f132e69caa4 <unknown>
#22 0x7f132e729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNDc0MDA2NzkuMTc0NTQ0OTc3MyJ9LCJhbm9uSWQiOiIwNTU1NGI4ZWY5MjM2YWVmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5NDYzODY3MzkzNzA1Mzk1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fea89cccea <unknown>
#1 0x55fea847d5f0 <unknown>
#2 0x55fea8463e86 <unknown>
#3 0x55fea846279a <unknown>
#4 0x55fea8462eff <unknown>
#5 0x55fea8462e54 <unknown>
#6 0x55fea84817ff <unknown>
#7 0x55fea85269aa <unknown>
#8 0x55fea84f4662 <unknown>
#9 0x55fea851a660 <unknown>
#10 0x55fea84f4433 <unknown>
#11 0x55fea84c0ea3 <unknown>
#12 0x55fea84c1b01 <unknown>
#13 0x55fea8991b3b <unknown>
#14 0x55fea8995a21 <unknown>
#15 0x55fea8978c32 <unknown>
#16 0x55fea8996594 <unknown>
#17 0x55fea895ceef <unknown>
#18 0x55fea89bad98 <unknown>
#19 0x55fea89baf76 <unknown>
#20 0x55fea89cbb36 <unknown>
#21 0x7f132e69caa4 <unknown>
#22 0x7f132e729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNDc0MDA2NzkuMTc0NTQ0OTc3MyJ9LCJhbm9uSWQiOiIwNTU1NGI4ZWY5MjM2YWVmIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNDc2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNDc2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzM4NzE5MTA0MTk0NDA3NyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fea89cccea <unknown>
#1 0x55fea847d5f0 <unknown>
#2 0x55fea8463e86 <unknown>
#3 0x55fea846279a <unknown>
#4 0x55fea8462eff <unknown>
#5 0x55fea8462e54 <unknown>
#6 0x55fea84817ff <unknown>
#7 0x55fea85269aa <unknown>
#8 0x55fea84f4662 <unknown>
#9 0x55fea851a660 <unknown>
#10 0x55fea84f4433 <unknown>
#11 0x55fea84c0ea3 <unknown>
#12 0x55fea84c1b01 <unknown>
#13 0x55fea8991b3b <unknown>
#14 0x55fea8995a21 <unknown>
#15 0x55fea8978c32 <unknown>
#16 0x55fea8996594 <unknown>
#17 0x55fea895ceef <unknown>
#18 0x55fea89bad98 <unknown>
#19 0x55fea89baf76 <unknown>
#20 0x55fea89cbb36 <unknown>
#21 0x7f132e69caa4 <unknown>
#22 0x7f132e729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NiIsInRpbWVzdGFtcCI6MTc0NTQ0OTc3ODEzMCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNDc0MDA2NzkuMTc0NTQ0OTc3MyJ9LCJhbm9uSWQiOiIwNTU1NGI4ZWY5MjM2YWVmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6Ijc4MzkyMzEzMjM3Nzg0ODQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fea89cccea <unknown>
#1 0x55fea847d5f0 <unknown>
#2 0x55fea8463e86 <unknown>
#3 0x55fea846279a <unknown>
#4 0x55fea8462eff <unknown>
#5 0x55fea8462e54 <unknown>
#6 0x55fea84817ff <unknown>
#7 0x55fea85269aa <unknown>
#8 0x55fea84f4662 <unknown>
#9 0x55fea851a660 <unknown>
#10 0x55fea84f4433 <unknown>
#11 0x55fea84c0ea3 <unknown>
#12 0x55fea84c1b01 <unknown>
#13 0x55fea8991b3b <unknown>
#14 0x55fea8995a21 <unknown>
#15 0x55fea8978c32 <unknown>
#16 0x55fea8996594 <unknown>
#17 0x55fea895ceef <unknown>
#18 0x55fea89bad98 <unknown>
#19 0x55fea89baf76 <unknown>
#20 0x55fea89cbb36 <unknown>
#21 0x7f132e69caa4 <unknown>
#22 0x7f132e729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e21c190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e21e310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e21c6d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc4NTMzODA4MS4xNzQ1NDQ5ODE2In0sImFub25JZCI6IjY1Y2M5MmI3ZmVjMmM2NzAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ1MTU3MDIwNzY4NzY3NTQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c936266cea <unknown>
#1 0x55c935d175f0 <unknown>
#2 0x55c935cfde86 <unknown>
#3 0x55c935cfc79a <unknown>
#4 0x55c935cfceff <unknown>
#5 0x55c935cfce54 <unknown>
#6 0x55c935d1b7ff <unknown>
#7 0x55c935dc09aa <unknown>
#8 0x55c935d8e662 <unknown>
#9 0x55c935db4660 <unknown>
#10 0x55c935d8e433 <unknown>
#11 0x55c935d5aea3 <unknown>
#12 0x55c935d5bb01 <unknown>
#13 0x55c93622bb3b <unknown>
#14 0x55c93622fa21 <unknown>
#15 0x55c936212c32 <unknown>
#16 0x55c936230594 <unknown>
#17 0x55c9361f6eef <unknown>
#18 0x55c936254d98 <unknown>
#19 0x55c936254f76 <unknown>
#20 0x55c936265b36 <unknown>
#21 0x7f0d4a29caa4 <unknown>
#22 0x7f0d4a329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc4NTMzODA4MS4xNzQ1NDQ5ODE2In0sImFub25JZCI6IjY1Y2M5MmI3ZmVjMmM2NzAifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjQ3NiIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjQ3NiJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM2MTg3MzgxMDYzNDQ5ODY0In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c936266cea <unknown>
#1 0x55c935d175f0 <unknown>
#2 0x55c935cfde86 <unknown>
#3 0x55c935cfc79a <unknown>
#4 0x55c935cfceff <unknown>
#5 0x55c935cfce54 <unknown>
#6 0x55c935d1b7ff <unknown>
#7 0x55c935dc09aa <unknown>
#8 0x55c935d8e662 <unknown>
#9 0x55c935db4660 <unknown>
#10 0x55c935d8e433 <unknown>
#11 0x55c935d5aea3 <unknown>
#12 0x55c935d5bb01 <unknown>
#13 0x55c93622bb3b <unknown>
#14 0x55c93622fa21 <unknown>
#15 0x55c936212c32 <unknown>
#16 0x55c936230594 <unknown>
#17 0x55c9361f6eef <unknown>
#18 0x55c936254d98 <unknown>
#19 0x55c936254f76 <unknown>
#20 0x55c936265b36 <unknown>
#21 0x7f0d4a29caa4 <unknown>
#22 0x7f0d4a329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNzg1MzM4MDgxLjE3NDU0NDk4MTYifSwiYW5vbklkIjoiNjVjYzkyYjdmZWMyYzY3MCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xiL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODE2OTQ2OTc5Mjk0MjI0OSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c936266cea <unknown>
#1 0x55c935d175f0 <unknown>
#2 0x55c935cfde86 <unknown>
#3 0x55c935cfc79a <unknown>
#4 0x55c935cfceff <unknown>
#5 0x55c935cfce54 <unknown>
#6 0x55c935d1b7ff <unknown>
#7 0x55c935dc09aa <unknown>
#8 0x55c935d8e662 <unknown>
#9 0x55c935db4660 <unknown>
#10 0x55c935d8e433 <unknown>
#11 0x55c935d5aea3 <unknown>
#12 0x55c935d5bb01 <unknown>
#13 0x55c93622bb3b <unknown>
#14 0x55c93622fa21 <unknown>
#15 0x55c936212c32 <unknown>
#16 0x55c936230594 <unknown>
#17 0x55c9361f6eef <unknown>
#18 0x55c936254d98 <unknown>
#19 0x55c936254f76 <unknown>
#20 0x55c936265b36 <unknown>
#21 0x7f0d4a29caa4 <unknown>
#22 0x7f0d4a329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NiIsInRpbWVzdGFtcCI6MTc0NTQ0OTgyMTE0MCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc4NTMzODA4MS4xNzQ1NDQ5ODE2In0sImFub25JZCI6IjY1Y2M5MmI3ZmVjMmM2NzAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNDE1MjU4MDMzNzcxMjg2MSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c936266cea <unknown>
#1 0x55c935d175f0 <unknown>
#2 0x55c935cfde86 <unknown>
#3 0x55c935cfc79a <unknown>
#4 0x55c935cfceff <unknown>
#5 0x55c935cfce54 <unknown>
#6 0x55c935d1b7ff <unknown>
#7 0x55c935dc09aa <unknown>
#8 0x55c935d8e662 <unknown>
#9 0x55c935db4660 <unknown>
#10 0x55c935d8e433 <unknown>
#11 0x55c935d5aea3 <unknown>
#12 0x55c935d5bb01 <unknown>
#13 0x55c93622bb3b <unknown>
#14 0x55c93622fa21 <unknown>
#15 0x55c936212c32 <unknown>
#16 0x55c936230594 <unknown>
#17 0x55c9361f6eef <unknown>
#18 0x55c936254d98 <unknown>
#19 0x55c936254f76 <unknown>
#20 0x55c936265b36 <unknown>
#21 0x7f0d4a29caa4 <unknown>
#22 0x7f0d4a329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e2a2490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ae1230f2449a4f6837d07abe1dffbbee
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e2a1f90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ae1230f2449a4f6837d07abe1dffbbee
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e2a1810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ae1230f2449a4f6837d07abe1dffbbee
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjkzMjk0NTg5LjE3NDU0NDk4NjIifSwiYW5vbklkIjoiZTc0MWJkYWZkOTVkN2QzMyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xiL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDc5MTExMzQzNzc1MDk3ODgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563deaee9cea <unknown>
#1 0x563dea99a5f0 <unknown>
#2 0x563dea980e86 <unknown>
#3 0x563dea97f79a <unknown>
#4 0x563dea97feff <unknown>
#5 0x563dea97fe54 <unknown>
#6 0x563dea99e7ff <unknown>
#7 0x563deaa439aa <unknown>
#8 0x563deaa11662 <unknown>
#9 0x563deaa37660 <unknown>
#10 0x563deaa11433 <unknown>
#11 0x563dea9ddea3 <unknown>
#12 0x563dea9deb01 <unknown>
#13 0x563deaeaeb3b <unknown>
#14 0x563deaeb2a21 <unknown>
#15 0x563deae95c32 <unknown>
#16 0x563deaeb3594 <unknown>
#17 0x563deae79eef <unknown>
#18 0x563deaed7d98 <unknown>
#19 0x563deaed7f76 <unknown>
#20 0x563deaee8b36 <unknown>
#21 0x7f139a69caa4 <unknown>
#22 0x7f139a729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5MzI5NDU4OS4xNzQ1NDQ5ODYyIn0sImFub25JZCI6ImU3NDFiZGFmZDk1ZDdkMzMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjh9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE1NTkwMzI5NTU1NTUyMDYzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563deaee9cea <unknown>
#1 0x563dea99a5f0 <unknown>
#2 0x563dea980e86 <unknown>
#3 0x563dea97f79a <unknown>
#4 0x563dea97feff <unknown>
#5 0x563dea97fe54 <unknown>
#6 0x563dea99e7ff <unknown>
#7 0x563deaa439aa <unknown>
#8 0x563deaa11662 <unknown>
#9 0x563deaa37660 <unknown>
#10 0x563deaa11433 <unknown>
#11 0x563dea9ddea3 <unknown>
#12 0x563dea9deb01 <unknown>
#13 0x563deaeaeb3b <unknown>
#14 0x563deaeb2a21 <unknown>
#15 0x563deae95c32 <unknown>
#16 0x563deaeb3594 <unknown>
#17 0x563deae79eef <unknown>
#18 0x563deaed7d98 <unknown>
#19 0x563deaed7f76 <unknown>
#20 0x563deaee8b36 <unknown>
#21 0x7f139a69caa4 <unknown>
#22 0x7f139a729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5MzI5NDU4OS4xNzQ1NDQ5ODYyIn0sImFub25JZCI6ImU3NDFiZGFmZDk1ZDdkMzMifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjo4fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI0NzYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI0NzYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxNTk2MjU5MTAxMDc0NDU2NSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563deaee9cea <unknown>
#1 0x563dea99a5f0 <unknown>
#2 0x563dea980e86 <unknown>
#3 0x563dea97f79a <unknown>
#4 0x563dea97feff <unknown>
#5 0x563dea97fe54 <unknown>
#6 0x563dea99e7ff <unknown>
#7 0x563deaa439aa <unknown>
#8 0x563deaa11662 <unknown>
#9 0x563deaa37660 <unknown>
#10 0x563deaa11433 <unknown>
#11 0x563dea9ddea3 <unknown>
#12 0x563dea9deb01 <unknown>
#13 0x563deaeaeb3b <unknown>
#14 0x563deaeb2a21 <unknown>
#15 0x563deae95c32 <unknown>
#16 0x563deaeb3594 <unknown>
#17 0x563deae79eef <unknown>
#18 0x563deaed7d98 <unknown>
#19 0x563deaed7f76 <unknown>
#20 0x563deaee8b36 <unknown>
#21 0x7f139a69caa4 <unknown>
#22 0x7f139a729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NiIsInRpbWVzdGFtcCI6MTc0NTQ0OTg2NzE2NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5MzI5NDU4OS4xNzQ1NDQ5ODYyIn0sImFub25JZCI6ImU3NDFiZGFmZDk1ZDdkMzMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNDQ0NTI5NjQ1NTE3MzUyMSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563deaee9cea <unknown>
#1 0x563dea99a5f0 <unknown>
#2 0x563dea980e86 <unknown>
#3 0x563dea97f79a <unknown>
#4 0x563dea97feff <unknown>
#5 0x563dea97fe54 <unknown>
#6 0x563dea99e7ff <unknown>
#7 0x563deaa439aa <unknown>
#8 0x563deaa11662 <unknown>
#9 0x563deaa37660 <unknown>
#10 0x563deaa11433 <unknown>
#11 0x563dea9ddea3 <unknown>
#12 0x563dea9deb01 <unknown>
#13 0x563deaeaeb3b <unknown>
#14 0x563deaeb2a21 <unknown>
#15 0x563deae95c32 <unknown>
#16 0x563deaeb3594 <unknown>
#17 0x563deae79eef <unknown>
#18 0x563deaed7d98 <unknown>
#19 0x563deaed7f76 <unknown>
#20 0x563deaee8b36 <unknown>
#21 0x7f139a69caa4 <unknown>
#22 0x7f139a729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_3.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab34ff8290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e5ed450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fab2e5ec310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/54d7572459405944485895042fc7e01f