ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2NTEyNDUwMjUuMTc0NTQzNjkyNiJ9LCJhbm9uSWQiOiIzYmY4YTliYzk2OTVkZjcyIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzMTkxMzg1MzMxMjU5NjcwNyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563bd18f5cea <unknown>
#1 0x563bd13a65f0 <unknown>
#2 0x563bd138ce86 <unknown>
#3 0x563bd138b79a <unknown>
#4 0x563bd138beff <unknown>
#5 0x563bd138be54 <unknown>
#6 0x563bd13aa7ff <unknown>
#7 0x563bd144f9aa <unknown>
#8 0x563bd141d662 <unknown>
#9 0x563bd1443660 <unknown>
#10 0x563bd141d433 <unknown>
#11 0x563bd13e9ea3 <unknown>
#12 0x563bd13eab01 <unknown>
#13 0x563bd18bab3b <unknown>
#14 0x563bd18bea21 <unknown>
#15 0x563bd18a1c32 <unknown>
#16 0x563bd18bf594 <unknown>
#17 0x563bd1885eef <unknown>
#18 0x563bd18e3d98 <unknown>
#19 0x563bd18e3f76 <unknown>
#20 0x563bd18f4b36 <unknown>
#21 0x7f718949caa4 <unknown>
#22 0x7f7189529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTY1MTI0NTAyNS4xNzQ1NDM2OTI2In0sImFub25JZCI6IjNiZjhhOWJjOTY5NWRmNzIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE4OTk1OTIxNzAwMDM0MDEzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563bd18f5cea <unknown>
#1 0x563bd13a65f0 <unknown>
#2 0x563bd138ce86 <unknown>
#3 0x563bd138b79a <unknown>
#4 0x563bd138beff <unknown>
#5 0x563bd138be54 <unknown>
#6 0x563bd13aa7ff <unknown>
#7 0x563bd144f9aa <unknown>
#8 0x563bd141d662 <unknown>
#9 0x563bd1443660 <unknown>
#10 0x563bd141d433 <unknown>
#11 0x563bd13e9ea3 <unknown>
#12 0x563bd13eab01 <unknown>
#13 0x563bd18bab3b <unknown>
#14 0x563bd18bea21 <unknown>
#15 0x563bd18a1c32 <unknown>
#16 0x563bd18bf594 <unknown>
#17 0x563bd1885eef <unknown>
#18 0x563bd18e3d98 <unknown>
#19 0x563bd18e3f76 <unknown>
#20 0x563bd18f4b36 <unknown>
#21 0x7f718949caa4 <unknown>
#22 0x7f7189529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc3IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2NTEyNDUwMjUuMTc0NTQzNjkyNiJ9LCJhbm9uSWQiOiIzYmY4YTliYzk2OTVkZjcyIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNDc3IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNDc3Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzYyNzI2Njk1NDcyNTEyNCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563bd18f5cea <unknown>
#1 0x563bd13a65f0 <unknown>
#2 0x563bd138ce86 <unknown>
#3 0x563bd138b79a <unknown>
#4 0x563bd138beff <unknown>
#5 0x563bd138be54 <unknown>
#6 0x563bd13aa7ff <unknown>
#7 0x563bd144f9aa <unknown>
#8 0x563bd141d662 <unknown>
#9 0x563bd1443660 <unknown>
#10 0x563bd141d433 <unknown>
#11 0x563bd13e9ea3 <unknown>
#12 0x563bd13eab01 <unknown>
#13 0x563bd18bab3b <unknown>
#14 0x563bd18bea21 <unknown>
#15 0x563bd18a1c32 <unknown>
#16 0x563bd18bf594 <unknown>
#17 0x563bd1885eef <unknown>
#18 0x563bd18e3d98 <unknown>
#19 0x563bd18e3f76 <unknown>
#20 0x563bd18f4b36 <unknown>
#21 0x7f718949caa4 <unknown>
#22 0x7f7189529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiaDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzciLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NyIsInRpbWVzdGFtcCI6MTc0NTQzNjkyOTQ0MSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE2NTEyNDUwMjUuMTc0NTQzNjkyNiJ9LCJhbm9uSWQiOiIzYmY4YTliYzk2OTVkZjcyIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjM2NDMzNTk4NjEzNDU5MDk1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563bd18f5cea <unknown>
#1 0x563bd13a65f0 <unknown>
#2 0x563bd138ce86 <unknown>
#3 0x563bd138b79a <unknown>
#4 0x563bd138beff <unknown>
#5 0x563bd138be54 <unknown>
#6 0x563bd13aa7ff <unknown>
#7 0x563bd144f9aa <unknown>
#8 0x563bd141d662 <unknown>
#9 0x563bd1443660 <unknown>
#10 0x563bd141d433 <unknown>
#11 0x563bd13e9ea3 <unknown>
#12 0x563bd13eab01 <unknown>
#13 0x563bd18bab3b <unknown>
#14 0x563bd18bea21 <unknown>
#15 0x563bd18a1c32 <unknown>
#16 0x563bd18bf594 <unknown>
#17 0x563bd1885eef <unknown>
#18 0x563bd18e3d98 <unknown>
#19 0x563bd18e3f76 <unknown>
#20 0x563bd18f4b36 <unknown>
#21 0x7f718949caa4 <unknown>
#22 0x7f7189529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833eeab090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833eea8650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833eea8d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xhL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiM2U3ZDMzYmViZmMyOTA0NyJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijk1NDg0MDAxMzY0MzY4NDEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e0ad240cea <unknown>
#1 0x55e0accf15f0 <unknown>
#2 0x55e0accd7e86 <unknown>
#3 0x55e0accd679a <unknown>
#4 0x55e0accd6eff <unknown>
#5 0x55e0accd6e54 <unknown>
#6 0x55e0accf57ff <unknown>
#7 0x55e0acd9a9aa <unknown>
#8 0x55e0acd68662 <unknown>
#9 0x55e0acd8e660 <unknown>
#10 0x55e0acd68433 <unknown>
#11 0x55e0acd34ea3 <unknown>
#12 0x55e0acd35b01 <unknown>
#13 0x55e0ad205b3b <unknown>
#14 0x55e0ad209a21 <unknown>
#15 0x55e0ad1ecc32 <unknown>
#16 0x55e0ad20a594 <unknown>
#17 0x55e0ad1d0eef <unknown>
#18 0x55e0ad22ed98 <unknown>
#19 0x55e0ad22ef76 <unknown>
#20 0x55e0ad23fb36 <unknown>
#21 0x7f1ab249caa4 <unknown>
#22 0x7f1ab2529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiIzZTdkMzNiZWJmYzI5MDQ3In0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiOTE1NTg1ODMwNTQ0MDYxNyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e0ad240cea <unknown>
#1 0x55e0accf15f0 <unknown>
#2 0x55e0accd7e86 <unknown>
#3 0x55e0accd679a <unknown>
#4 0x55e0accd6eff <unknown>
#5 0x55e0accd6e54 <unknown>
#6 0x55e0accf57ff <unknown>
#7 0x55e0acd9a9aa <unknown>
#8 0x55e0acd68662 <unknown>
#9 0x55e0acd8e660 <unknown>
#10 0x55e0acd68433 <unknown>
#11 0x55e0acd34ea3 <unknown>
#12 0x55e0acd35b01 <unknown>
#13 0x55e0ad205b3b <unknown>
#14 0x55e0ad209a21 <unknown>
#15 0x55e0ad1ecc32 <unknown>
#16 0x55e0ad20a594 <unknown>
#17 0x55e0ad1d0eef <unknown>
#18 0x55e0ad22ed98 <unknown>
#19 0x55e0ad22ef76 <unknown>
#20 0x55e0ad23fb36 <unknown>
#21 0x7f1ab249caa4 <unknown>
#22 0x7f1ab2529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc3IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjNlN2QzM2JlYmZjMjkwNDcifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI0NzciLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI0NzciXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMTU1ODMzMDIyMzAxMTUwNCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e0ad240cea <unknown>
#1 0x55e0accf15f0 <unknown>
#2 0x55e0accd7e86 <unknown>
#3 0x55e0accd679a <unknown>
#4 0x55e0accd6eff <unknown>
#5 0x55e0accd6e54 <unknown>
#6 0x55e0accf57ff <unknown>
#7 0x55e0acd9a9aa <unknown>
#8 0x55e0acd68662 <unknown>
#9 0x55e0acd8e660 <unknown>
#10 0x55e0acd68433 <unknown>
#11 0x55e0acd34ea3 <unknown>
#12 0x55e0acd35b01 <unknown>
#13 0x55e0ad205b3b <unknown>
#14 0x55e0ad209a21 <unknown>
#15 0x55e0ad1ecc32 <unknown>
#16 0x55e0ad20a594 <unknown>
#17 0x55e0ad1d0eef <unknown>
#18 0x55e0ad22ed98 <unknown>
#19 0x55e0ad22ef76 <unknown>
#20 0x55e0ad23fb36 <unknown>
#21 0x7f1ab249caa4 <unknown>
#22 0x7f1ab2529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiaDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzciLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NyIsInRpbWVzdGFtcCI6MTc0NTQzNjk2NDkxMiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEwNzY2OTg0NjEuMTc0NTQzNjk2MyJ9LCJhbm9uSWQiOiIzZTdkMzNiZWJmYzI5MDQ3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjkwMDI0MjU5NTY5NTE0MjkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e0ad240cea <unknown>
#1 0x55e0accf15f0 <unknown>
#2 0x55e0accd7e86 <unknown>
#3 0x55e0accd679a <unknown>
#4 0x55e0accd6eff <unknown>
#5 0x55e0accd6e54 <unknown>
#6 0x55e0accf57ff <unknown>
#7 0x55e0acd9a9aa <unknown>
#8 0x55e0acd68662 <unknown>
#9 0x55e0acd8e660 <unknown>
#10 0x55e0acd68433 <unknown>
#11 0x55e0acd34ea3 <unknown>
#12 0x55e0acd35b01 <unknown>
#13 0x55e0ad205b3b <unknown>
#14 0x55e0ad209a21 <unknown>
#15 0x55e0ad1ecc32 <unknown>
#16 0x55e0ad20a594 <unknown>
#17 0x55e0ad1d0eef <unknown>
#18 0x55e0ad22ed98 <unknown>
#19 0x55e0ad22ef76 <unknown>
#20 0x55e0ad23fb36 <unknown>
#21 0x7f1ab249caa4 <unknown>
#22 0x7f1ab2529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833e942690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833e940390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f833e9401d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d5dd070873024eed1f960028a6822b32